language: shell

git:
  depth: 2

install:
  - rsync -uar --delete-after {.,}* "${HOME}"

script:
  - bash -x .dotfiles_setup.sh
  # - bash -x .dotfiles_setup.sh install

after_script:
  - bash -x .dotfiles_setup.sh test
